linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - gofmt
    - goimports
    - misspell

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
  misspell:
    locale: US

issues:
  exclude-dirs:
    - vendor
  max-issues-per-linter: 50
  max-same-issues: 10
